/* eslint-disable no-unused-vars */

export default (i18n, admin) => [
  {
    icon: "mdi-view-dashboard",
    text: i18n.t("menu.dashboard"),
    link: "/",
  },
  { divider: true },
  admin.getResourceLink("users"),
  { divider: true },
  admin.getResourceLink("members"),
  { divider: true },
  admin.getResourceLink("conference"),
  { divider: true },
  admin.getResourceLink("conference officials"),
  { divider: true },
  admin.getResourceLink("conference schedules"),
  { divider: true },
  admin.getResourceLink("conference applications"),
  { divider: true },
  admin.getResourceLink("payments"),
  { divider: true },
  admin.getResourceLink("award and citations"),
  { divider: true },
  admin.getResourceLink("announcements"),
  { divider: true },
  admin.getResourceLink("aluminia"),
  { divider: true },
  admin.getResourceLink("profiles"),
];
